---
title: "Procesamiento de Datos"
author: "Javier Marzo Caballero, Iván Pérez Alonso, Yordano Rodriguez Bernal, Iván Jiménez Mañó y Héctor Balbastre Aparisi"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Librerías

```{r, warning=FALSE, message=FALSE}
library(sf)
library(tidyverse)
library(stringr)
```

# Exploración de los datos

## Distritos

```{r}
distritos <- st_read("Datos_sin_procesar/distritos.geojson")
distritos <- distritos[,-4]
head(distritos)

# Número de registros del dataframe
nrow(distritos)
# Si hay algún NA en el dataframe
any(is.na(distritos))
# Número de valores NA en cada columna
colSums(is.na(distritos))
```

```{r}
st_write(distritos, "Datos_Procesados/distritos.geojson")
```


## Hoteles

```{r}
hoteles <- read.csv("Datos_sin_procesar/hoteles_por_distritos.csv", sep=";")
hoteles <- hoteles[,-c(11, 13)]
head(hoteles)
# Número de registros del dataframe
nrow(hoteles)
# Si hay algún NA en el dataframe
any(is.na(hoteles))
# Número de valores NA en cada columna
colSums(is.na(hoteles))

#Este data frame lo utilizaremos exclusivamente para la parte de gráficos y datos, no 
#es necesario proyectarlo en Qgis.
```

```{r}
st_write(hoteles, "Datos_Procesados/hoteles.geojson")
```


## EMT

```{r}
emt <- st_read("Datos_sin_procesar/EMT.geojson")
emt <- emt[,-c(3:5)]
head(emt)
# Número de registros del dataframe
nrow(emt)
# Si hay algún NA en el dataframe
any(is.na(emt))
# Número de valores NA en cada columna
colSums(is.na(emt))
```

```{r}
st_write(emt, "Datos_Procesados/EMT.geojson")
```


## Espacios verdes

```{r}
verde <- st_read("Datos_sin_procesar/espacios_verdes.geojson")
head(verde)
# Número de registros del dataframe
nrow(verde)
# Si hay algún NA en el dataframe
any(is.na(verde))
# Número de valores NA en cada columna
colSums(is.na(verde))
# Conservaremos estos datos como elemento estético, no es necesario para el objetivo del trabajo.
```

```{r}
st_write(verde, "Datos_Procesados/espacios_verdes.geojson")
```


## Fuentes de agua públicas

```{r}
fuentes <- st_read("Datos_sin_procesar/fuentes_agua.geojson")
head(fuentes)
# Número de registros del dataframe
nrow(fuentes)
# Si hay algún NA en el dataframe
any(is.na(fuentes))
# Número de valores NA en cada columna
colSums(is.na(fuentes))
```

```{r}
st_write(fuentes, "Datos_Procesados/fuentes_agua.geojson")
```


## Monumentos turísticos

```{r}
monumentos <- st_read("Datos_sin_procesar/monumentos_turisticos.geojson")

monumentos_repetidos <- c('ESGLÉSIA DEL SAGRAT COR DE JESÚS (PATRAIX)',"ESGLÉSIA PARROQUIAL DE L'ANTIC CONVENT DE SANTA MARIA DE JESÚS",'PALAU DE LA MÚSICA','ANTIC MONESTIR DE SANT MIQUEL DELS REIS','ESGLÉSIA PARROQUIAL DE LA MARE DE DÉU DEL SAGRAT COR','ESGLÉSIA PARROQUIAL DELS SANTS ABDÓ I SENENT','ESGLÉSIA PARROQUIAL DE SANTA ANNA (BORBOTÓ)','ESGLÉSIA PARROQUIAL DELS SANTS ABDÓ I SENENT','ESGLÉSIA PARROQUIAL DE LA MARE DE DÉU DE GRÀCIA - LA TORRE',"ESGLÉSIA DEL CRIST DE L'AGONIA DEL FORN D'ALCEDO",'ESGLÉSIA PARROQUIAL DE LA MARE DE DÉU DEL ROSARI (LEPANT-CASTELLAR)','BIOPARC','CIUTAT DE LES ARTS I LES CIÈNCIES','PALAU DE CONGRESSOS','12-PARROQUIA SANTIAGO APÓSTOL','CASA MUSEU BLASCO IBÁÑEZ','ASIL DE SANT JOAN DE DÉU','ESGLÉSIA PARROQUIAL DE LA MARE DE DÉU DELS ÀNGELS (EL CABANYAL)','MUSEU DE LA SETMANA SANTA MARINERA')

monumentos <- monumentos %>% dplyr::filter(!(nombre %in% monumentos_repetidos))

iglesias1 <- monumentos %>%
  filter(str_detect(nombre, regex("iglesia|església", ignore_case = TRUE)))
iglesias1$id <- c(1:55)

palacios_museos1 <- monumentos %>%
  filter(str_detect(nombre, regex("palacio|palau|museo|museu", ignore_case = TRUE)))
palacios_museos1$id <- c(1:44)


iglesias1 <- iglesias1[,c(10,2,9)]
palacios_museos1 <- palacios_museos1[,c(10,2,9)]


monumentos <- monumentos[!monumentos$nombre %in% iglesias1$nombre, ]
monumentos <- monumentos[!monumentos$nombre %in% palacios_museos1$nombre, ]

parroquias_conventos1 <- monumentos %>%
  filter(str_detect(nombre, regex("parroquia|parròquia|convent", ignore_case = TRUE)))
parroquias_conventos1$id <- c(1:12)

parroquias_conventos1 <- parroquias_conventos1[,c(10,2,9)]
monumentos <- monumentos[!monumentos$nombre %in% parroquias_conventos1$nombre, ]

head(monumentos)
# Número de registros del dataframe
nrow(monumentos)
# Si hay algún NA en el dataframe
any(is.na(monumentos))
# Número de valores NA en cada columna
colSums(is.na(monumentos))
```

```{r}
st_write(monumentos, "Datos_Procesados/monumentos_turisticos.geojson")
```

## Recursos turísticos

```{r}
recursos <- st_read("Datos_sin_procesar/recursos_turisticos.geojson")
recursos <- recursos[,-3]

iglesias2 <- recursos %>%
  filter(str_detect(nombre, regex("iglesia|església", ignore_case = TRUE)))
iglesias2$id <- c(56:68)

palacios_museos2 <- recursos %>%
  filter(str_detect(nombre, regex("palacio|palau|museo|museu", ignore_case = TRUE)))
palacios_museos2$id <- c(45:53)


iglesias2 <- iglesias2[,c(12,2,11)]
palacios_museos2 <- palacios_museos2[,c(12,2,11)]


recursos <- recursos[!recursos$nombre %in% iglesias2$nombre, ]
recursos <- recursos[!recursos$nombre %in% palacios_museos2$nombre, ]

parroquias_conventos2 <- recursos %>%
  filter(str_detect(nombre, regex("parroquia|parròquia|convent", ignore_case = TRUE)))
parroquias_conventos2$id <- c(13:19)

parroquias_conventos2 <- parroquias_conventos2[,c(12,2,11)]
recursos <- recursos[!recursos$nombre %in% parroquias_conventos2$nombre, ]

head(recursos)
# Número de registros del dataframe
nrow(recursos)
# Si hay algún NA en el dataframe
any(is.na(recursos))
# Número de valores NA en cada columna
colSums(is.na(recursos))
```

```{r}
st_write(recursos, "Datos_Procesados/recursos_turisticos.geojson")
```


## Iglesias

```{r}
iglesias <- rbind(iglesias1,iglesias2)

head(iglesias)
# Número de registros del dataframe
nrow(iglesias)
# Si hay algún NA en el dataframe
any(is.na(iglesias))
# Número de valores NA en cada columna
colSums(is.na(iglesias))
```

```{r}
st_write(iglesias, "Datos_Procesados/iglesias.geojson")
```

## Palacios y museos
```{r}
palacios_y_museos <- rbind(palacios_museos1,palacios_museos2)

head(palacios_y_museos)
# Número de registros del dataframe
nrow(palacios_y_museos)
# Si hay algún NA en el dataframe
any(is.na(palacios_y_museos))
# Número de valores NA en cada columna
colSums(is.na(palacios_y_museos))
```

```{r}
st_write(palacios_y_museos, "Datos_Procesados/palacios_y_museos.geojson")
```

## Parroquias y conventos

```{r}
parroquias_conventos <- rbind(parroquias_conventos1,parroquias_conventos2)

head(parroquias_conventos)
# Número de registros del dataframe
nrow(parroquias_conventos)
# Si hay algún NA en el dataframe
any(is.na(parroquias_conventos))
# Número de valores NA en cada columna
colSums(is.na(parroquias_conventos))
```


```{r}
st_write(parroquias_conventos, "Datos_Procesados/parroquias_conventos.geojson")
```

## Zonas de actividades

```{r}
actividades <- st_read("Datos_sin_procesar/zonas_actividades.geojson")

head(actividades)
# Número de registros del dataframe
nrow(actividades)
# Si hay algún NA en el dataframe
any(is.na(actividades))
# Número de valores NA en cada columna
colSums(is.na(actividades))
# Estos datos son sobre las fallas, por lo que no nos interesan.
```


## Zonas de juego infantil

```{r}
juego <- st_read("Datos_sin_procesar/zonas_juego_infantiles.geojson")
juego <- juego[, -c(8, 9, 10, 11, 12)] # Columnas que no sirven

head(juego)
# Número de registros del dataframe
nrow(juego)
# Si hay algún NA en el dataframe
any(is.na(juego))
# Número de valores NA en cada columna
colSums(is.na(juego))
```

```{r}
st_write(juego, "Datos_Procesados/juegos_infantiles.geojson")
```

